config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_tmux.conf:
    src: tmux.conf
    dst: ~/.tmux.conf
    chmod: '600'
  d_omf:
    src: config/omf
    dst: ~/.config/omf
    chmod: '775'
profiles:
  office:
    dotfiles:
    - d_nvim
    - f_tmux.conf
    - d_omf
  gin:
    dotfiles:
    - d_nvim
    - f_tmux.conf
    - d_omf
